package bcc

const dashboardHTML = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>BAFT Command Center</title>
<style>
:root{color-scheme:dark;font-family:Inter,system-ui,sans-serif;background:#090b10;color:#eef1f6}
body{margin:0;background:radial-gradient(circle at top,#182238,#090b10 42%);min-height:100vh}
.wrap{max-width:1280px;margin:auto;padding:24px}.top{display:flex;justify-content:space-between;align-items:center;gap:12px}
h1{font-size:24px;margin:0}.muted{color:#8e9aaf}.card{background:#111722;border:1px solid #263147;border-radius:16px;padding:18px;margin-top:16px}
.grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.grid input,.grid select,select{background:#0b1019;border:1px solid #2a3650;color:#fff;border-radius:10px;padding:10px}
button{background:#e8b54a;color:#16100a;border:0;border-radius:10px;padding:10px 14px;font-weight:700;cursor:pointer}button.alt{background:#25324a;color:#e8eef8}
table{width:100%;border-collapse:collapse;margin-top:12px}th,td{text-align:left;padding:10px;border-bottom:1px solid #222c3e;font-size:13px;vertical-align:top}
.badge{display:inline-block;padding:4px 9px;border-radius:999px;background:#263147;text-transform:uppercase;font-size:11px}.up{background:#123e2c;color:#92f0bf}.down{background:#4b2026;color:#ffabb6}.unknown{background:#37333a;color:#d9cedd}
.route{display:flex;gap:6px;align-items:center;margin:3px 0;white-space:nowrap}.actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:12px}
.kpis{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.kpi{background:#0b1019;border-radius:12px;padding:12px}.kpi b{display:block;font-size:20px;margin-top:4px}
canvas{width:100%;height:240px;background:#0b1019;border-radius:12px;margin-top:12px}
@media(max-width:820px){.grid,.kpis{grid-template-columns:1fr 1fr}.wrap{padding:12px}.tablewrap{overflow:auto}}@media(max-width:520px){.grid,.kpis{grid-template-columns:1fr}}
</style></head>
<body><div class="wrap">
<div class="top"><div><h1>BAFT Command Center</h1><div class="muted">Operational monitoring, finance & hardening · Step 5.4</div></div><button class="alt" onclick="setToken()">Admin Token</button></div>

<div class="card">
<div class="top"><b>Live Monitoring</b><span id="monitorTime" class="muted">—</span></div>
<div class="kpis" style="margin-top:12px"><div class="kpi">Nodes<b id="kNodes">0</b></div><div class="kpi">UP<b id="kUp">0</b></div><div class="kpi">DOWN<b id="kDown">0</b></div><div class="kpi">UNKNOWN<b id="kUnknown">0</b></div></div>
<div class="tablewrap"><table><thead><tr><th>Node</th><th>Status</th><th>Noise RTT</th><th>Health latency</th><th>Error rate</th><th>Last Seen</th><th>Sessions</th><th>Routes</th></tr></thead><tbody id="monitorRows"></tbody></table></div>
</div>

<div class="card"><div class="top"><b>7-Day Traffic & Uptime</b><select id="historyNode" onchange="loadHistory()"></select></div><canvas id="historyCanvas" width="1100" height="240"></canvas><div id="historyLegend" class="muted" style="margin-top:8px">Select a node.</div></div>

<div class="card"><b>Register / update node</b><div class="grid" style="margin-top:12px">
<input id="nid" placeholder="node id"><input id="alias" placeholder="alias"><input id="addr" placeholder="management host:port">
<input id="path4" placeholder="path IPv4 (optional)"><input id="path6" placeholder="path IPv6 (optional)">
<select id="role"><option value="foreign">foreign</option><option value="worker">worker</option><option value="master">master</option></select>
<input id="pub" placeholder="public key"><input id="agentEnv" placeholder="agent token env name"><button onclick="saveNode()">Save Node</button>
</div></div>

<div class="card"><b>Add a server over SSH</b>
<div class="muted" style="margin-top:6px">1) read the host key and compare its fingerprint with your provider's panel, 2) confirm, 3) install the agent. The SSH password or key is sent once over this connection and is never stored or logged.</div>
<div class="grid" style="margin-top:12px">
<input id="bsId" placeholder="node id (e.g. ex-1)"><input id="bsAlias" placeholder="alias"><select id="bsRole"><option value="foreign">foreign (EX)</option><option value="worker">worker (IR)</option><option value="master">master (IR)</option></select><span></span>
<input id="bsHost" placeholder="host or IP"><input id="bsPort" placeholder="ssh port" value="22"><input id="bsUser" placeholder="ssh user" value="root"><button class="alt" onclick="bsScan()">1. Read host key</button>
</div>
<div id="bsFp" class="muted" style="margin-top:10px;font-family:monospace;word-break:break-all">—</div>
<label style="display:block;margin-top:8px"><input type="checkbox" id="bsOk" onchange="bsGate()"> I compared this fingerprint with the server's real one</label>
<div class="grid" style="margin-top:12px;grid-template-columns:1fr 2fr 1fr">
<input id="bsPass" type="password" autocomplete="off" placeholder="ssh password"><textarea id="bsKey" rows="3" autocomplete="off" spellcheck="false" placeholder="or paste an SSH private key (PEM)" style="background:#0b1019;border:1px solid #2a3650;color:#fff;border-radius:10px;padding:10px"></textarea><input id="bsPhrase" type="password" autocomplete="off" placeholder="key passphrase (if any)">
</div>
<div class="actions"><button id="bsGo" onclick="bsRun()" disabled>2. Install agent</button></div>
<pre id="bsOut" class="muted" style="white-space:pre-wrap;margin-top:10px"></pre></div>

<div class="card"><div class="top"><b>Existing tunnels (discovery)</b><span><button class="alt" onclick="dcStart()">Discover all</button> <button class="alt" onclick="loadDiscovery()">Refresh</button></span></div>
<div class="muted">Report only. Discovery reads each node and never adopts, changes, restarts or deletes anything. States: MANAGED, DRIFTED, MISSING, DISCOVERED_UNMANAGED, OWNERSHIP_CONFLICT, UNKNOWN.</div>
<div class="tablewrap"><table><thead><tr><th>Node</th><th>Unit</th><th>State</th><th>Why</th></tr></thead><tbody id="dcRows"></tbody></table></div></div>
<div class="card"><div class="top"><b>Layered health</b><button class="alt" onclick="loadHealth()">Refresh</button></div>
<div class="muted">A state changes only after several consistent samples. NOT_ASSESSED means BCC has no signal for that layer; UNKNOWN means no evidence yet or for a while. Neither is DOWN.</div>
<div class="tablewrap"><table><thead><tr><th>Node</th><th>Overall</th><th>Layers</th><th>Recent transitions</th></tr></thead><tbody id="hlRows"></tbody></table></div></div>
<div class="card"><div class="top"><b>Tunnels</b><button class="alt" onclick="loadTunnels()">Refresh</button></div>
<div class="grid" style="margin-top:12px">
<select id="tnEx"></select><select id="tnIr"></select><input id="tnPort" placeholder="EX port" value="8443"><button onclick="tnPlan()">Preview plan</button>
</div>
<div class="muted" style="margin-top:8px">Preview shows exactly what will change, the checks that must pass and how it rolls back. Deploying uses the reviewed plan by its hash: if anything changed meanwhile, nothing is deployed and you review the new plan.</div><div id="tnPlan" style="margin-top:12px"></div>
<div class="tablewrap"><table><thead><tr><th>ID</th><th>EX</th><th>IR</th><th>Phase</th><th>Detail</th><th></th></tr></thead><tbody id="tnRows"></tbody></table></div></div>

<div class="card"><div class="top"><b>Route Doctor / عیب‌یاب مسیر</b><button class="alt" onclick="rdRun()">Run diagnosis / اجرای تشخیص</button></div>
<div class="muted">Read-only diagnosis of an active BAFT tunnel. It reports the first causally blocking stage and never changes firewall, ports, certificates, routing or tunnel state. / تشخیص فقط‌خواندنی است و هیچ تنظیمی را تغییر نمی‌دهد.</div>
<div class="grid" style="margin-top:10px"><select id="rdTunnel"><option value="">active tunnel…</option></select></div>
<div id="rdResult" class="muted" style="margin-top:10px">No diagnosis selected. / هنوز تشخیصی اجرا نشده است.</div></div>
<div class="card"><div class="top"><b>Automatic Path Discovery / کشف خودکار مسیر</b><div><span class="badge up">AUTO</span> <button class="alt" onclick="pdRun()">Refresh graph now</button></div></div>
<div class="muted">BCC inventories every enrolled node and measures directed IPv4/IPv6 paths automatically. Only FULL_DATA edges can become routes; TCP/TLS-only and byte-ceiling paths are rejected. No country, provider or server name is hard-coded.</div>
<div id="pdState" class="muted" style="margin-top:8px">Waiting for discovery…</div>
<div style="margin-top:12px"><b>Connectivity Matrix / ماتریس اتصال</b><div class="muted">Rows are sources; columns are destinations. PASS requires fresh FULL_DATA evidence. Stale evidence is never green.</div><div id="pmMatrix" class="tablewrap"></div></div>
<div class="tablewrap"><table><thead><tr><th>From → To</th><th>Recommended path</th><th>Hops</th><th>RTT</th></tr></thead><tbody id="pgRows"></tbody></table></div>
<details style="margin-top:12px"><summary>Advanced manual probe / تست دستی پیشرفته</summary><div class="grid" style="margin-top:12px"><select id="ppSrc"></select><select id="ppDst"></select><select id="ppFamily"><option value="4">IPv4</option><option value="6">IPv6</option></select><input id="ppPorts" value="22,80,443,8443,9443,49152" placeholder="candidate ports"><button onclick="ppRun()">Run pair probe</button></div>
<div class="tablewrap"><table><thead><tr><th>Path</th><th>Family</th><th>Phase</th><th>Recommended</th><th>Evidence</th></tr></thead><tbody id="ppRows"></tbody></table></div></details></div>

<div class="card"><div class="top"><b>Cluster Nodes</b><span id="count" class="muted"></span></div>
<div class="tablewrap"><table><thead><tr><th></th><th>Alias</th><th>ID</th><th>Address</th><th>Role</th><th>Health Check</th><th>Last Check</th><th>Security</th></tr></thead><tbody id="rows"></tbody></table></div>
<div class="actions"><button onclick="deploy()">One-Click Deploy Selected</button><button class="alt" onclick="loadAll()">Refresh</button></div></div>

<div class="card"><b>Recent Jobs</b><div id="jobs" class="muted" style="margin-top:10px">Admin token required.</div></div>
<div class="card"><div class="top"><b>Immutable Audit Log</b><button class="alt" onclick="loadAudit()">Refresh</button></div>
<div class="muted" style="margin-top:8px">Read-only hash-chained admin events. No delete/edit action is exposed.</div>
<div class="tablewrap"><table><thead><tr><th>#</th><th>UTC</th><th>IP</th><th>Action</th><th>Target</th><th>Outcome</th><th>Hash</th></tr></thead><tbody id="auditRows"></tbody></table></div></div>
<div class="card"><div class="top"><b>Node Finance</b><button class="alt" onclick="setFinance()">Set Versioned Rate</button></div>
<div class="tablewrap"><table><thead><tr><th>Node</th><th>Traffic GiB</th><th>Cost</th><th>Revenue</th><th>Profit</th></tr></thead><tbody id="financeRows"></tbody></table></div></div>

<div class="card"><div class="top"><b>Finance Reports</b><span class="muted">Default timezone: Asia/Tehran</span></div>
<div class="grid" style="margin-top:12px">
<select id="reportPeriod"><option value="daily">Daily</option><option value="monthly">Monthly</option></select>
<input id="reportFrom" type="date"><input id="reportTo" type="date"><input id="reportTZ" value="Asia/Tehran" placeholder="Timezone">
<button onclick="loadFinanceReport()">Load Report</button><button class="alt" onclick="downloadFinanceCSV()">Download CSV</button>
</div>
<div class="tablewrap"><table><thead><tr><th>Period</th><th>Scope</th><th>Node</th><th>Ingress</th><th>Egress</th><th>Cost</th><th>Revenue</th><th>Profit</th><th>Currency</th></tr></thead><tbody id="reportRows"></tbody></table></div>
</div>
</div>
<script>
const q=s=>document.querySelector(s);let nodes=[],monitor=[];
function token(){return localStorage.getItem('bccToken')||''}
function setToken(){localStorage.setItem('bccToken',prompt('BCC admin token')||'');loadAll()}
function ah(){return {'Authorization':'Bearer '+token(),'Content-Type':'application/json'}}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function ago(v){if(!v||new Date(v).getFullYear()<2000)return '—';let d=(Date.now()-new Date(v).getTime())/1000;if(d<60)return Math.max(0,Math.round(d))+'s ago';if(d<3600)return Math.round(d/60)+'m ago';return Math.round(d/3600)+'h ago'}
function rate(v){return (Number(v||0)/1000).toFixed(2)+'/min'}
function routeHTML(rs){if(!rs||!rs.length)return '<span class=muted>—</span>';return rs.map(r=>'<div class=route><span class="badge '+esc(r.status)+'">'+esc(r.status)+'</span><span>'+esc(r.route_id)+'</span><span class=muted>'+((r.latency_ms??-1)>=0?esc(r.latency_ms)+' ms':'—')+' · '+esc(r.probe_kind||'')+'</span></div>').join('')}
async function loadNodes(){if(!token())return;let r=await fetch('/api/nodes',{headers:ah()});if(!r.ok)return;nodes=await r.json();q('#count').textContent=nodes.length+' nodes';ppFill();q('#rows').innerHTML=nodes.map(n=>'<tr><td><input type=checkbox class=pick value="'+esc(n.id)+'"></td><td>'+esc(n.alias)+'</td><td>'+esc(n.id)+'</td><td>'+esc(n.address)+'</td><td>'+esc(n.role)+'</td><td><span class="badge '+esc(n.health)+'">'+esc(n.health)+'</span> '+((n.latency_ms??-1)>=0?esc(n.latency_ms)+' ms':'')+'</td><td>'+esc(n.last_checked||'—')+'</td><td>'+(n.revoked?'<span class="badge down">REVOKED</span>':'<button class="alt" onclick="rotateToken(\''+esc(n.id)+'\')">Rotate</button> <button onclick="revokeNode(\''+esc(n.id)+'\')">Kill</button>')+'</td></tr>').join('')}
async function loadMonitoring(){if(!token())return;let r=await fetch('/api/monitoring',{headers:ah()});if(!r.ok)return;monitor=await r.json();q('#monitorTime').textContent=new Date().toLocaleTimeString();q('#kNodes').textContent=monitor.length;q('#kUp').textContent=monitor.filter(x=>x.status==='up').length;q('#kDown').textContent=monitor.filter(x=>x.status==='down').length;q('#kUnknown').textContent=monitor.filter(x=>x.status==='unknown').length;
q('#monitorRows').innerHTML=monitor.map(n=>'<tr><td><b>'+esc(n.alias)+'</b><div class=muted>'+esc(n.node_id)+'</div></td><td><span class="badge '+esc(n.status)+'">'+esc(n.status)+'</span></td><td>'+((n.noise_latency_ms??-1)>=0?esc(n.noise_latency_ms)+' ms':'—')+'<div class=muted>Noise RTT</div></td><td>'+((n.latency_ms??-1)>=0?esc(n.latency_ms)+' ms':'—')+'<div class=muted>TCP health-check</div></td><td>'+rate(n.handshake_error_rate_milli_per_min)+'</td><td>'+ago(n.last_seen)+'</td><td>'+esc(n.active_sessions||0)+'</td><td>'+routeHTML(n.routes)+'</td></tr>').join('');
let sel=q('#historyNode'),cur=sel.value;sel.innerHTML=monitor.map(n=>'<option value="'+esc(n.node_id)+'">'+esc(n.alias)+'</option>').join('');if(cur&&monitor.some(n=>n.node_id===cur))sel.value=cur;if(!sel.dataset.loaded&&monitor.length){sel.dataset.loaded='1';loadHistory()}}
async function loadJobs(){if(!token())return;let r=await fetch('/api/jobs',{headers:ah()});if(!r.ok)return;let j=await r.json();q('#jobs').innerHTML=j.slice(0,20).map(x=>'<div>'+esc(x.id)+' · '+esc(x.type)+' · '+esc(x.node_id)+' · <b>'+esc(x.status)+'</b></div>').join('')||'No jobs'}
async function loadAudit(){if(!token())return;let r=await fetch('/api/audit',{headers:ah()});if(!r.ok)return;let a=await r.json();q('#auditRows').innerHTML=a.slice().reverse().map(x=>'<tr><td>'+esc(x.sequence)+'</td><td>'+esc(x.timestamp)+'</td><td>'+esc(x.remote_ip)+'</td><td>'+esc(x.action)+'</td><td>'+esc(x.target||'—')+'</td><td>'+esc(x.outcome)+'</td><td class=muted>'+esc((x.hash||'').slice(0,16))+'…</td></tr>').join('')}
function micros(v){return (Number(v||0)/1000000).toFixed(4)}
async function loadFinance(){if(!token())return;let r=await fetch('/api/finance',{headers:ah()});if(!r.ok)return;let fs=await r.json();q('#financeRows').innerHTML=fs.map(x=>{let n=nodes.find(n=>n.id===x.node_id);let gib=(Number(x.ingress_bytes||0)+Number(x.egress_bytes||0))/1073741824;return '<tr><td>'+esc(n?.alias||x.node_id)+'</td><td>'+gib.toFixed(3)+'</td><td>'+micros(x.cost_micros)+'</td><td>'+micros(x.revenue_micros)+'</td><td>'+micros(x.profit_micros)+'</td></tr>'}).join('')}
async function loadHistory(){if(!token())return;let id=q('#historyNode').value;if(!id)return;let r=await fetch('/api/history?node_id='+encodeURIComponent(id),{headers:ah()});if(!r.ok)return;drawHistory(await r.json())}
function drawHistory(points){let c=q('#historyCanvas'),x=c.getContext('2d'),w=c.width,h=c.height;x.clearRect(0,0,w,h);x.strokeStyle='#263147';x.strokeRect(0,0,w,h);if(!points.length){q('#historyLegend').textContent='No history yet.';return}let vals=points.map(p=>Number(p.ingress_bytes||0)+Number(p.egress_bytes||0)),max=Math.max(1,...vals),step=w/Math.max(1,points.length-1);x.lineWidth=2;x.strokeStyle='#e8b54a';x.beginPath();points.forEach((p,i)=>{let y=h-20-(vals[i]/max)*(h-40);if(i===0)x.moveTo(0,y);else x.lineTo(i*step,y)});x.stroke();x.strokeStyle='#63d39a';x.beginPath();points.forEach((p,i)=>{let up=p.node_health==='up';let y=up?15:h-15;if(i===0)x.moveTo(0,y);else x.lineTo(i*step,y)});x.stroke();q('#historyLegend').textContent='Gold: cumulative traffic · Green: health-check uptime · '+points.length+' samples / last 7 days'}
async function saveNode(){let body={ID:q('#nid').value,Alias:q('#alias').value,Address:q('#addr').value,path_ipv4:q('#path4').value.trim(),path_ipv6:q('#path6').value.trim(),Role:q('#role').value,PublicKey:q('#pub').value,AgentTokenEnv:q('#agentEnv').value};let r=await fetch('/api/nodes',{method:'POST',headers:ah(),body:JSON.stringify(body)});if(!r.ok)alert(await r.text());else loadAll()}
async function deploy(){let ids=[...document.querySelectorAll('.pick:checked')].map(x=>x.value);let version=prompt('BAFT version');if(!version)return;let r=await fetch('/api/deploy',{method:'POST',headers:ah(),body:JSON.stringify({node_ids:ids,version})});alert(r.ok?'Deploy jobs queued':await r.text());loadJobs();loadAudit()}
async function revokeNode(node_id){let reason=prompt('Kill Switch reason','manual security revoke');if(reason===null)return;let r=await fetch('/api/nodes/revoke',{method:'POST',headers:ah(),body:JSON.stringify({node_id,reason})});alert(r.ok?'Node revoked immediately':await r.text());loadNodes();loadAudit()}
async function rotateToken(node_id){let agent_token_env=prompt('Environment variable containing the NEW agent token');if(!agent_token_env)return;let grace=prompt('Old-token grace seconds (0-900)','60');if(grace===null)return;let r=await fetch('/api/nodes/rotate-token',{method:'POST',headers:ah(),body:JSON.stringify({node_id,agent_token_env,grace_seconds:Number(grace)})});alert(r.ok?'Token rotation activated':await r.text());loadNodes();loadAudit()}
async function setFinance(){let node_id=prompt('Node ID');if(!node_id)return;let cost=prompt('Cost micros per GiB','0');let revenue=prompt('Revenue micros per GiB','0');let currency=prompt('Currency code','IRR')||'IRR';let effective_from=prompt('Effective from RFC3339 (blank = now)','')||'';if(cost===null||revenue===null)return;let r=await fetch('/api/finance',{method:'POST',headers:ah(),body:JSON.stringify({node_id,cost_micros_per_gib:Number(cost),revenue_micros_per_gib:Number(revenue),currency,effective_from})});alert(r.ok?'Versioned finance rate saved':await r.text());loadFinance();loadAudit()}
function reportURL(format){let p=q('#reportPeriod').value,f=q('#reportFrom').value,t=q('#reportTo').value,z=q('#reportTZ').value||'Asia/Tehran';return '/api/finance/report?period='+encodeURIComponent(p)+'&from='+encodeURIComponent(f)+'&to='+encodeURIComponent(t)+'&tz='+encodeURIComponent(z)+(format?'&format='+format:'')}
async function loadFinanceReport(){if(!token())return;let r=await fetch(reportURL(''),{headers:ah()});if(!r.ok){alert(await r.text());return}let data=await r.json();q('#reportRows').innerHTML=data.rows.map(x=>'<tr><td>'+esc(x.period)+'</td><td>'+esc(x.scope)+'</td><td>'+esc(x.node_id||'ALL')+'</td><td>'+esc(x.ingress_bytes)+'</td><td>'+esc(x.egress_bytes)+'</td><td>'+esc(x.cost_micros)+'</td><td>'+esc(x.revenue_micros)+'</td><td>'+esc(x.profit_micros)+'</td><td>'+esc(x.currency)+'</td></tr>').join('')}
async function downloadFinanceCSV(){if(!token())return;let r=await fetch(reportURL('csv'),{headers:ah()});if(!r.ok){alert(await r.text());return}let blob=await r.blob(),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='baft-finance-'+q('#reportPeriod').value+'.csv';a.click();URL.revokeObjectURL(u)}
function initReportDates(){let d=new Date(),to=d.toISOString().slice(0,10),first=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),1)).toISOString().slice(0,10);q('#reportFrom').value=first;q('#reportTo').value=to}
function bsGate(){q('#bsGo').disabled=!q('#bsOk').checked||!q('#bsFp').dataset.fp}
async function bsScan(){q('#bsOk').checked=false;q('#bsFp').dataset.fp='';bsGate();let r=await fetch('/api/bootstrap/hostkey',{method:'POST',headers:ah(),body:JSON.stringify({host:q('#bsHost').value.trim(),port:Number(q('#bsPort').value)||22})});let t=await r.text();if(!r.ok){q('#bsFp').textContent=t;return}let d=JSON.parse(t);q('#bsFp').dataset.fp=d.fingerprint;q('#bsFp').textContent=d.key_type+'  '+d.fingerprint}
async function bsRun(){let fp=q('#bsFp').dataset.fp;if(!fp||!q('#bsOk').checked)return;let body={node_id:q('#bsId').value.trim(),alias:q('#bsAlias').value.trim(),role:q('#bsRole').value,host:q('#bsHost').value.trim(),port:Number(q('#bsPort').value)||22,user:q('#bsUser').value.trim(),host_key_fingerprint:fp,password:q('#bsPass').value,private_key:q('#bsKey').value,passphrase:q('#bsPhrase').value};if(body.private_key)body.password='';q('#bsGo').disabled=true;q('#bsOut').textContent='Installing… this can take a few minutes.';let r=await fetch('/api/bootstrap',{method:'POST',headers:ah(),body:JSON.stringify(body)});let t=await r.text();body.password=body.private_key=body.passphrase='';q('#bsPass').value=q('#bsKey').value=q('#bsPhrase').value='';q('#bsOk').checked=false;q('#bsFp').dataset.fp='';bsGate();if(r.ok){try{t=JSON.parse(t).output||'Installed.'}catch(e){}}q('#bsOut').textContent=(r.ok?'OK\n':'FAILED\n')+t;loadAll()}
function tnFill(){let opt=(role)=>nodes.filter(n=>role.includes(n.role)&&!n.revoked).map(n=>'<option value="'+esc(n.id)+'">'+esc(n.alias||n.id)+' ('+esc(n.id)+')</option>').join('');let ex=q('#tnEx'),ir=q('#tnIr'),a=ex.value,b=ir.value;ex.innerHTML='<option value="">EX node…</option>'+opt(['foreign']);ir.innerHTML='<option value="">IR node…</option>'+opt(['worker','master']);ex.value=a;ir.value=b}
let tnPlanHash='',tnPlanReq=null;
function tnReq(){return {ex_node:q('#tnEx').value,ir_node:q('#tnIr').value,port:Number(q('#tnPort').value)||8443}}
function tnShowPlan(p){tnPlanHash=p.hash;tnPlanReq=p.request;let h='<div class="card" style="margin:0"><b>Deployment plan</b> <span class="badge '+(p.ok?'up':'down')+'">'+(p.ok?'ready':'blocked')+'</span><div class="muted" style="font-family:monospace;word-break:break-all;margin:6px 0">plan '+esc(p.hash)+'</div>';h+='<table><thead><tr><th>Gate</th><th>Status</th><th>Detail</th></tr></thead><tbody>'+p.gates.map(g=>'<tr><td>'+esc(g.name)+'</td><td><span class="badge '+(g.status==='PASS'?'up':g.status==='WARN'?'unknown':'down')+'">'+esc(g.status)+'</span></td><td>'+esc(g.detail)+'</td></tr>').join('')+'</tbody></table>';h+=p.nodes.map(n=>'<div style="margin-top:10px"><b>'+esc(n.role.toUpperCase())+' '+esc(n.node_id)+'</b> <span class="muted">generation '+esc(n.generation_from)+' → '+esc(n.generation_to)+(n.generation_note?' ('+esc(n.generation_note)+')':'')+'</span><ul>'+n.changes.map(c=>'<li>'+esc(c)+'</li>').join('')+'</ul></div>').join('');h+='<div><b>Steps</b><ol>'+p.steps.map(c=>'<li>'+esc(c)+'</li>').join('')+'</ol></div><div><b>Verified before it counts as deployed</b><ul>'+p.verify.map(c=>'<li>'+esc(c)+'</li>').join('')+'</ul></div><div><b>Rollback</b><ul>'+p.rollback.map(c=>'<li>'+esc(c)+'</li>').join('')+'</ul></div>';h+='<div class="actions"><button '+(p.ok?'':'disabled ')+'onclick="tnDeploy()">Deploy this plan</button><button class="alt" onclick="tnClearPlan()">Discard</button></div></div>';q('#tnPlan').innerHTML=h}
function tnClearPlan(){tnPlanHash='';tnPlanReq=null;q('#tnPlan').innerHTML=''}
async function tnPlan(){let body=tnReq();if(!body.ex_node||!body.ir_node){alert('Choose the EX and IR nodes');return}let r=await fetch('/api/tunnels/plan',{method:'POST',headers:ah(),body:JSON.stringify(body)});let t=await r.text();if(!r.ok){alert(t);return}tnShowPlan(JSON.parse(t));loadAudit()}
async function tnDeploy(){if(!tnPlanHash||!tnPlanReq)return;let body=Object.assign({},tnPlanReq,{plan_hash:tnPlanHash});let r=await fetch('/api/tunnels',{method:'POST',headers:ah(),body:JSON.stringify(body)});let t=await r.text();if(r.status===409){try{let d=JSON.parse(t);alert(d.error);tnShowPlan(d.plan)}catch(e){alert(t)}return}if(!r.ok){alert(t);return}tnClearPlan();loadTunnels();loadAudit()}
async function tnRotate(id){if(!confirm('Rotate the TLS certificate of tunnel '+id+'? The IR trusts old + new until the new certificate is confirmed; any failure before that rolls back.'))return;let r=await fetch('/api/tunnels/rotate-cert',{method:'POST',headers:ah(),body:JSON.stringify({tunnel_id:id})});let t=await r.text();if(!r.ok){alert(t);return}try{alert('rotation '+JSON.parse(t).id+' started')}catch(e){}loadAudit()}
async function tnCancel(id){let reason=prompt('Cancel and roll back tunnel '+id+'. Reason (optional)','');if(reason===null)return;let r=await fetch('/api/tunnels/cancel',{method:'POST',headers:ah(),body:JSON.stringify({id,reason})});if(!r.ok)alert(await r.text());loadTunnels();loadAudit()}
async function tnDecommission(id){let pr=await fetch('/api/tunnels/decommission/plan',{method:'POST',headers:ah(),body:JSON.stringify({id})});let txt=await pr.text();if(!pr.ok){alert(txt);return}let p=JSON.parse(txt);if(!p.ok){alert('Decommission is blocked:\n'+p.gates.filter(g=>g.status==='FAIL').map(g=>g.name+': '+g.detail).join('\n'));loadAudit();return}let msg=p.warning+'\n\nOrder: IR route first, then EX listener.\nPlan: '+p.hash+'\n\nContinue?';if(!confirm(msg))return;let r=await fetch('/api/tunnels/decommission',{method:'POST',headers:ah(),body:JSON.stringify({id,plan_hash:p.hash})});let out=await r.text();if(r.status===409){try{let d=JSON.parse(out);alert(d.error+'\nReview a fresh decommission plan before retrying.')}catch(e){alert(out)}return}if(!r.ok){alert(out);return}loadTunnels();loadAudit()}
async function tnDrift(id){let r=await fetch('/api/tunnels/drift?id='+encodeURIComponent(id),{method:'POST',headers:ah()});if(!r.ok)alert(await r.text());loadTunnels();loadAudit()}
function ppFill(){let options='<option value="">node…</option>'+nodes.filter(n=>!n.revoked).map(n=>'<option value="'+esc(n.id)+'">'+esc(n.alias||n.id)+'</option>').join('');for(let id of ['ppSrc','ppDst']){let e=q('#'+id);if(!e)continue;let old=e.value;e.innerHTML=options;if(nodes.some(n=>n.id===old))e.value=old}}
function ppCls(c){return c==='FULL_DATA'?'up':(['BYTE_CEILING','CONNECT_ONLY','HANDSHAKE_ONLY','TIMEOUT_UNREACHABLE','LOCAL_CONFLICT'].includes(c)?'down':'unknown')}
async function ppRun(){let ports=q('#ppPorts').value.split(',').map(x=>Number(x.trim())).filter(x=>Number.isInteger(x)&&x>0&&x<65536);let body={source_node:q('#ppSrc').value,destination_node:q('#ppDst').value,family:q('#ppFamily').value,candidate_ports:[...new Set(ports)]};if(!body.source_node||!body.destination_node||body.source_node===body.destination_node){alert('Choose two different enrolled nodes');return}let r=await fetch('/api/path-probes',{method:'POST',headers:ah(),body:JSON.stringify(body)});let t=await r.text();if(!r.ok){alert(t);return}loadPathProbes();loadAudit()}
async function pdRun(){let r=await fetch('/api/path-discovery',{method:'POST',headers:ah(),body:JSON.stringify({candidate_ports:[]})});let t=await r.text();if(!r.ok&&!t.includes('already active'))alert(t);loadPathGraph();loadPathMatrix();loadPathProbes();loadAudit()}
async function loadPathGraph(){if(!token()||!q('#pgRows'))return;let [gr,dr]=await Promise.all([fetch('/api/path-graph',{headers:ah()}),fetch('/api/path-discovery',{headers:ah()})]);if(gr.ok){let g=await gr.json();q('#pgRows').innerHTML=(g.recommendations||[]).map(r=>{let hops=(r.hops||[]).map(h=>esc(h.source_node)+' → '+esc(h.destination_node)+' / IPv'+esc(h.family)+' :'+esc(h.port)).join(' · ');return '<tr><td>'+esc(r.source_node)+' → '+esc(r.destination_node)+'</td><td>'+hops+'</td><td>'+esc((r.hops||[]).length)+(r.direct?' · direct':' · multi-hop')+'</td><td>'+esc(r.total_rtt_ms||0)+' ms</td></tr>'}).join('')||'<tr><td colspan=4 class=muted>No FULL_DATA route evidence yet.</td></tr>'}if(dr.ok){let ds=await dr.json(),d=ds[0];q('#pdState').textContent=d?('Latest discovery: '+d.phase+' · '+(d.probe_ids||[]).length+' path candidates · '+ago(d.updated_at)):'Automatic discovery will start when at least two enrolled nodes are available.'}}
function pmCls(st){return st==='PASS'?'up':(st==='FAIL'||st==='DEGRADED'?'down':'unknown')}
function pmCell(c){if(!c)return '<span class="badge unknown">NOT_ASSESSED</span>';let ev=(c.candidates||[]).map(x=>'IPv'+esc(x.family)+' :'+esc(x.port)+' · '+esc(x.class)+(x.connect_rtt_ms?' · '+esc(x.connect_rtt_ms)+' ms':'')+(x.byte_ceiling?' · ceiling '+esc(x.byte_ceiling)+' B':'')+(x.detail?' · '+esc(x.detail):'')+' · '+esc(x.age_seconds)+'s old').join(' | ');return '<details><summary><span class="badge '+pmCls(c.state)+'">'+esc(c.state)+'</span></summary><div class=muted>'+esc(ev||'No completed evidence')+'</div></details>'}
async function loadPathMatrix(){if(!token()||!q('#pmMatrix'))return;let r=await fetch('/api/path-matrix',{headers:ah()});if(!r.ok)return;let m=await r.json(),by={};(m.cells||[]).forEach(c=>by[c.source_node+'\0'+c.destination_node]=c);let ns=m.nodes||[];let h='<table><thead><tr><th>From \ To</th>'+ns.map(n=>'<th>'+esc(n)+'</th>').join('')+'</tr></thead><tbody>';h+=ns.map(src=>'<tr><th>'+esc(src)+'</th>'+ns.map(dst=>src===dst?'<td class=muted>—</td>':'<td>'+pmCell(by[src+'\0'+dst])+'</td>').join('')+'</tr>').join('');q('#pmMatrix').innerHTML=h+'</tbody></table>'}
async function loadPathProbes(){if(!token()||!q('#ppRows'))return;let r=await fetch('/api/path-probes',{headers:ah()});if(!r.ok)return;let ps=await r.json();q('#ppRows').innerHTML=ps.map(p=>{let ev=(p.candidates||[]).map(c=>'<div><span class="badge '+ppCls(c.class)+'">'+esc(c.class||'PENDING')+'</span> '+esc(c.port)+(c.byte_ceiling?' · ceiling '+esc(c.byte_ceiling)+' B':'')+(c.connect_rtt_ms?' · '+esc(c.connect_rtt_ms)+' ms':'')+'<div class=muted>'+esc(c.detail||'')+'</div></div>').join('');return '<tr><td>'+esc(p.source_node)+' → '+esc(p.destination_node)+'</td><td>IPv'+esc(p.family)+'</td><td><span class="badge '+(p.phase==='complete'?'up':p.phase==='failed'?'down':'unknown')+'">'+esc(p.phase)+'</span></td><td>'+(p.recommended_port?'<b>'+esc(p.recommended_port)+'</b>':'—')+'</td><td>'+ev+'</td></tr>'}).join('')||'<tr><td colspan=5 class=muted>No path probes yet.</td></tr>'}
function rdFill(ts){let e=q('#rdTunnel');if(!e)return;let old=e.value;e.innerHTML='<option value="">active tunnel…</option>'+ts.filter(t=>t.phase==='active').map(t=>'<option value="'+esc(t.id)+'">'+esc(t.id)+' · '+esc(t.ir_node)+' → '+esc(t.ex_node)+'</option>').join('');if(ts.some(t=>t.id===old&&t.phase==='active'))e.value=old}
function rdRender(r){let stages=(r.stages||[]).map(s=>'<div><span class="badge '+(s.state==='PASS'?'up':s.state==='FAIL'?'down':'unknown')+'">'+esc(s.state)+'</span> <b>'+esc(s.stage)+'</b> <span class=muted>'+esc(s.detail||'')+(s.reference?' · '+esc(s.reference):'')+'</span></div>').join('');q('#rdResult').innerHTML='<div><b>'+esc(r.summary_en||'')+'</b><div>'+esc(r.summary_fa||'')+'</div><div class=muted>Evidence '+esc(r.evidence_digest||'')+' · '+esc(r.id||'')+'</div></div>'+stages}
async function rdRun(){let id=q('#rdTunnel').value;if(!id){alert('Choose an active tunnel');return}let r=await fetch('/api/route-doctor',{method:'POST',headers:ah(),body:JSON.stringify({tunnel_id:id})});let t=await r.text();if(!r.ok){alert(t);return}rdRender(JSON.parse(t));loadAudit()}
function dcCls(st){return st==='MANAGED'?'up':(st==='DRIFTED'||st==='MISSING'||st==='OWNERSHIP_CONFLICT'?'down':'unknown')}
async function dcStart(){let r=await fetch('/api/discovery?all=1',{method:'POST',headers:ah()});if(!r.ok)alert(await r.text());loadDiscovery();loadAudit()}
async function loadDiscovery(){if(!token())return;let r=await fetch('/api/discovery',{headers:ah()});if(!r.ok)return;let d=await r.json();q('#dcRows').innerHTML=(d.nodes||[]).map(n=>{let head=n.pending?'<span class=muted>running…</span>':(n.problem?'<span class=muted>'+esc(n.problem)+'</span>':(n.at?'<span class=muted>'+esc(n.at)+'</span>':'<span class=muted>not run</span>'));let ins=n.instances||[];if(!ins.length)return '<tr><td>'+esc(n.node_id)+'</td><td colspan=3>'+head+'</td></tr>';return ins.map((v,i)=>'<tr><td>'+(i===0?esc(n.node_id)+'<div>'+head+'</div>':'')+'</td><td>'+esc(v.unit)+(v.primary?' <span class=muted>(primary)</span>':'')+'</td><td><span class="badge '+dcCls(v.state)+'">'+esc(v.state)+'</span></td><td>'+esc((v.reasons||[]).join('; '))+'</td></tr>').join('')}).join('')}
function hlCls(st){return st==='UP'?'up':(st==='DOWN'?'down':'unknown')}
async function loadHealth(){if(!token())return;let r=await fetch('/api/health',{headers:ah()});if(!r.ok)return;let d=await r.json();q('#hlRows').innerHTML=(d.nodes||[]).map(n=>'<tr><td>'+esc(n.alias||n.node_id)+(n.conformity?'<div class=muted>config: '+esc(n.conformity)+'</div>':'')+'</td><td><span class="badge '+hlCls(n.overall)+'">'+esc(n.overall)+'</span>'+((n.why||[]).length?'<div class=muted>'+esc(n.why.join('; '))+'</div>':'')+'</td><td>'+(n.layers||[]).map(l=>'<div title="'+esc(l.evidence||l.note||'')+'"><span class="badge '+hlCls(l.state)+'">'+esc(l.layer)+' '+esc(l.state)+'</span> <span class=muted>'+esc(l.name)+(l.evidence?' · '+esc(l.evidence):'')+(l.note?' · '+esc(l.note):'')+'</span></div>').join('')+'</td><td>'+((n.transitions||[]).slice().reverse().map(t=>'<div class=muted>'+esc(t.at)+' · '+esc(t.layer)+' '+esc(t.from)+' → '+esc(t.to)+' · '+esc(t.reason)+' · '+esc(t.evidence)+'</div>').join('')||'<span class=muted>none</span>')+'</td></tr>').join('')}
async function loadTunnels(){if(!token())return;let r=await fetch('/api/tunnels',{headers:ah()});if(!r.ok)return;let ts=await r.json();tnFill();rdFill(ts);q('#tnRows').innerHTML=ts.map(t=>{let final=['active','superseded','rolled_back','rollback_failed','decommissioned','decommission_failed'].includes(t.phase);let cls=t.phase==='active'?'up':(t.phase==='rolled_back'||t.phase==='rollback_failed'||t.phase==='decommission_failed'?'down':'unknown');let actions='';if(t.phase==='active')actions='<button class="alt" data-id="'+esc(t.id)+'" onclick="tnDrift(this.dataset.id)">Check drift</button> <button class="alt" data-id="'+esc(t.id)+'" onclick="tnRotate(this.dataset.id)">Rotate cert</button> <button class="alt" data-id="'+esc(t.id)+'" onclick="tnDecommission(this.dataset.id)">Decommission</button>'+(t.cert_epoch?'<div class=muted>cert epoch '+esc(t.cert_epoch)+'</div>':'');else if(t.phase==='decommission_failed')actions='<button class="alt" data-id="'+esc(t.id)+'" onclick="tnDecommission(this.dataset.id)">Retry decommission</button>';else if(!final)actions='<button class="alt" data-id="'+esc(t.id)+'" onclick="tnCancel(this.dataset.id)">Cancel</button>';return '<tr><td>'+esc(t.id)+'</td><td>'+esc(t.ex_node)+'</td><td>'+esc(t.ir_node)+'</td><td><span class="badge '+cls+'">'+esc(t.phase)+'</span></td><td>'+esc(t.error||'')+(t.drift?'<div class=muted>drift: <b>'+esc(t.drift.state)+'</b> · '+esc(Object.entries(t.drift.nodes||{}).filter(e=>e[1].state!=='IN_SYNC').map(e=>e[0]+': '+e[1].state+' ('+(e[1].problems||[]).join('; ')+')').join(' | '))+'</div>':'')+((t.evidence||[]).length?'<details><summary class=muted>evidence ('+t.evidence.length+')</summary>'+t.evidence.map(e=>'<div class=muted>'+esc(e.step)+' · '+esc(e.node)+' · '+(e.ok?'OK':'FAILED')+(e.problems?' · '+esc(e.problems.join('; ')):'')+'</div>').join('')+'</details>':'')+'</td><td>'+actions+'</td></tr>'}).join('')}
async function loadAll(){await loadNodes();await Promise.all([loadMonitoring(),loadJobs(),loadFinance(),loadAudit(),loadTunnels(),loadHealth(),loadDiscovery(),loadPathProbes(),loadPathGraph(),loadPathMatrix()])}
const fastPollMS=10000,slowPollMS=30000;let fastPollTimer=null,slowPollTimer=null;
async function loadFast(){if(document.hidden)return;await Promise.all([loadMonitoring(),loadTunnels(),loadHealth()])}
async function loadSlow(){if(document.hidden)return;await Promise.all([loadFinance(),loadDiscovery()])}
function stopPolling(){if(fastPollTimer!==null){clearInterval(fastPollTimer);fastPollTimer=null}if(slowPollTimer!==null){clearInterval(slowPollTimer);slowPollTimer=null}}
function startPolling(){stopPolling();if(document.hidden)return;fastPollTimer=setInterval(loadFast,fastPollMS);slowPollTimer=setInterval(loadSlow,slowPollMS)}
document.addEventListener('visibilitychange',()=>{if(document.hidden){stopPolling();return}loadFast();loadSlow();startPolling()});
initReportDates();loadAll();startPolling();
</script></body></html>`
