#!/usr/bin/env bash
# Generate THIRD_PARTY_LICENSES.md: the license and notice texts of every
# third-party module linked into the released binaries, plus the Go standard
# library. MIT, BSD and Apache-2.0 require these notices to ship with binary
# distributions.
#
#   scripts/third_party_licenses.sh            write THIRD_PARTY_LICENSES.md
#   scripts/third_party_licenses.sh --check    fail if the file is stale or a
#                                              module carries a copyleft license
set -euo pipefail

cd "$(dirname "$0")/.."
out=THIRD_PARTY_LICENSES.md
mode=${1:-write}

# Keep in step with scripts/release/build.sh.
pkgs=(./cmd/baft ./cmd/baft-pair ./cmd/baft-bcc ./cmd/baft-agent)
arches=(amd64 arm64)

go mod download

mods=$(
  for arch in "${arches[@]}"; do
    CGO_ENABLED=0 GOOS=linux GOARCH=$arch go list -deps \
      -f '{{with .Module}}{{if not .Main}}{{.Path}}@{{.Version}}{{end}}{{end}}' "${pkgs[@]}"
  done | sort -u
)

modcache=$(go env GOMODCACHE)
goroot=$(go env GOROOT)
license_files='^(LICENSE|LICENCE|COPYING|NOTICE|PATENTS)'

tmp=$(mktemp)
trap 'rm -f "$tmp"' EXIT
{
  echo "# Third-party licenses"
  echo
  echo "BAFT release binaries ($(IFS=,; echo "${pkgs[*]##*/}" | sed 's/,/, /g')) include the third-party"
  echo "software listed below. Each component is used under the license reproduced"
  echo "here. BAFT's own license is in LICENSE."
  echo
  echo "Generated by scripts/third_party_licenses.sh; do not edit by hand."
  echo
  echo "| Component | Version |"
  echo "|---|---|"
  echo "| Go standard library | toolchain pinned in go.mod |"
  for m in $mods; do echo "| ${m%@*} | ${m#*@} |"; done
  echo
  echo "---"
  echo
  echo "## Go standard library"
  for f in LICENSE PATENTS; do
    echo
    echo "### $f"
    echo
    echo '```'
    cat "$goroot/$f"
    echo '```'
  done
  for m in $mods; do
    path=${m%@*}
    ver=${m#*@}
    # Module cache escapes upper-case letters as !lower.
    esc=$(printf '%s' "$path" | sed 's/\([A-Z]\)/!\L\1/g')
    dir="$modcache/$esc@$ver"
    echo
    echo "---"
    echo
    echo "## $path $ver"
    found=0
    for f in $(ls -1 "$dir" | grep -iE "$license_files" | sort); do
      found=1
      echo
      echo "### $f"
      echo
      echo '```'
      cat "$dir/$f"
      echo '```'
    done
    if [ "$found" = 0 ]; then
      echo "error: no license file found for $m" >&2
      exit 1
    fi
  done
} >"$tmp"

# Strong-copyleft licenses are incompatible with BAFT's proprietary license.
# Match license titles, not mentions: MPL-2.0 (file-level, allowed for
# unmodified use) names the GPL family in its "Secondary License" definition.
if grep -nE '^[[:space:]]*GNU (AFFERO |LESSER )?GENERAL PUBLIC LICENSE|^[[:space:]]*Server Side Public License' "$tmp" >&2; then
  echo "error: a linked module carries a copyleft license; review before release" >&2
  exit 1
fi

if [ "$mode" = "--check" ]; then
  if ! cmp -s "$tmp" "$out"; then
    echo "error: $out is stale; run scripts/third_party_licenses.sh and commit the result" >&2
    exit 1
  fi
  echo "$out is up to date ($(echo "$mods" | wc -l | tr -d ' ') modules)"
else
  cp "$tmp" "$out"
  echo "wrote $out ($(echo "$mods" | wc -l | tr -d ' ') modules)"
fi
